title:             La Educación del Siglo XXI
email:             jornadaseducacion.comisionorg@ gmail.com
description:       V Jornadas. Una Educación para el Siglo XXI. Miradas desde las Ciencias y las Artes.
author:            Educación Siglo XXI

# Social Profiles
twitter_username:  EDUCACION_SXXI
github_username:   EducacionSiglo21
facebook_username: FacebookUser

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
